# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-UTC_SLS
version:      0.000
version_from: lib/Time/UTC_SLS.pm
installdirs:  site
requires:
    Math::BigRat:                  0.04
    Time::UTC:                     0.001

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
